In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('iris.csv')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
df['species'].value_counts()

setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64

In [4]:
df.tail()

sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [5]:
df.shape

(150, 5)

In [6]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [8]:
df.describe().T

count      mean       std  min  25%   50%  75%  max
sepal_length  150.0  5.843333  0.828066  4.3  5.1  5.80  6.4  7.9
sepal_width   150.0  3.054000  0.433594  2.0  2.8  3.00  3.3  4.4
petal_length  150.0  3.758667  1.764420  1.0  1.6  4.35  5.1  6.9
petal_width   150.0  1.198667  0.763161  0.1  0.3  1.30  1.8  2.5

In [9]:
df.duplicated().any()

True

In [10]:
df.drop_duplicates(inplace=True)

In [11]:
df.duplicated().any()

False

In [12]:
df.shape

(147, 5)

In [13]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [14]:
from pandas.core.common import random_state
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=42)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((117, 4), (30, 4), (117,), (30,))

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.neighbors import KNeighborsClassifier
m1=LogisticRegression()
m2=DecisionTreeClassifier()
m3=RandomForestClassifier(n_estimators=80)
m4=ExtraTreesClassifier(n_estimators=80)
from sklearn.metrics import confusion_matrix,classification_report,roc_curve,roc_auc_score,f1_score
model=[m1,m2,m3,m4]
for i in model:
  i.fit(x_train,y_train)
  y_pred=i.predict(x_test)
  y_pred_prob=i.predict_proba(x_test)
  cm=confusion_matrix(y_test,y_pred)
  print(cm)
  print('training score ',i.score(x_train,y_train))
  print('testing ',i.score(x_test,y_test))
  print('ROC Score:',roc_auc_score(y_test,y_pred_prob,multi_class='ovo',average='weighted'))
  print('F1 Score:',f1_score(y_test,y_pred,average=None))
  print(classification_report(y_test,y_pred))
  print('-----------------------------------------------------------------------------------------------------------------------------------------------------------------------')

E:\anconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]
training score  0.9743589743589743
testing  0.9666666666666667
ROC Score: 1.0
F1 Score: [1.         0.94736842 0.95238095]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      0.90      0.95        10
   virginica       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]
training score  1.0
testing  0.9666666666666667
ROC Score: 0.9749999999999999
F1 Score: [1.         0.94736842 0.95238095]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.0

In [16]:
newValue=[[6.7,3.2,1.4,0.2]]
res=m4.predict(newValue)
print(res)

['setosa']


E:\anconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(


In [17]:
import pickle as pkl
pkl.dump(m4,open('iris1.pkl','wb'))

In [18]:
mod=pkl.load(open("iris1.pkl","rb"))
print(type(mod))

<class 'sklearn.ensemble._forest.ExtraTreesClassifier'>
